/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobileplanmgmt.presentation.view.mobileplan;

import mobileplanmgmt.domain.model.MobilePlan;
import mobileplanmgmt.presentation.controller.MobilePlanController;

/**
 *
 * @author Zekiloni
 */
public class SingleMobilePlanView extends javax.swing.JFrame {

    private MobilePlanController mobilePlanController;
    
    private MobilePlan mobilePlan;
    
    private boolean isEditingActive = false;
    
    /**
     * Creates new form SingleMobilePlanView
     */
    public SingleMobilePlanView(MobilePlanController mobilePlanController, MobilePlan mobilePlan) {
        this.mobilePlanController = mobilePlanController;
        this.mobilePlan = mobilePlan;
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mobilePlanToStringOutput = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mobilePlanToStringOutput.setColumns(20);
        mobilePlanToStringOutput.setRows(5);
        mobilePlanToStringOutput.setEnabled(false);
        jScrollPane1.setViewportView(mobilePlanToStringOutput);

        jButton1.setText("Close");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMobilePlanSingleActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(176, 0, 1));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMobilePlanSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMobilePlanSingleActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeMobilePlanSingleActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        this.mobilePlanController.deleteMobilePlan(this.mobilePlan.getId());
        this.setVisible(false);
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mobilePlanToStringOutput;
    // End of variables declaration//GEN-END:variables

    private void load() {
        mobilePlanToStringOutput.setText(this.mobilePlan.toString());
    }
}
